[broker]
address = "localhost:9092"
security_protocol = "PLAINTEXT"
cert_path = ""
sasl_mechanism = "not-used"
sasl_username = "not-used"
sasl_password = "not-used"
topic = "ccx.ocp.results"
group = "test-consumer-group"
enabled = true

[logging]
debug = true
log_level = ""

[output]
verbose = false
